version: "3.9"
services:
    db:
        image: postgres:14.1-alpine
        container_name: playground_db
        env_file:
            - .env
        ports:
            - "5432:5432"
    frontend:
        build: frontend
        ports:
            - "3000:3000"
        container_name: playground_frontend
        volumes:
            - "./frontend:/app"
            - "/app/node_modules"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CI=true
        depends_on:
            - backend
    backend:
        build: backend
        ports:
            - "3001:3001"
        container_name: playground_backend
        volumes:
            - "./backend:/app"
            - "/app/node_modules"
        env_file:
            - .env
        depends_on:
            - db
    simulation:
        build: ../mesh_communication/backend
        ports:
        - "8080:8080"
    
